name: Release

on:
  push:
    branches:
      - "master"
      - "pre"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  package:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build dependencies in cache
        run: yarn --immutable

      - name: Release
        run: yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.AMBIMAX_GITHUB_RELEASE_TOKEN }}
